#!/bin/bash
# 保存到 /usr/local/bin 使用
# 命令使用 xsync2 fileName ip1 ip2 ip3
#1 获取输入参数个数，如果没有参数，直接退出
pcount=$#
if((pcount==0)); then
echo no args;
exit;
fi

#2 获取文件名称
p1=$1
fname=`basename $p1`
echo fname=$fname

#3 获取上级目录到绝对路径
pdir=`d -P $(dirname $p1);pwd`
echo pdir=$pdir

#4 获取当前用户名称
user=`whoami`

#5 循环，这里host根据自己的节点数和主机名设置
time=1
for name in $@; do
	if((time > 1));then
       		#echo $pdir/$fname $user@hadoop$host:$pdir
        	echo --------------- $name ----------------
        	echo rsync -rvl $pdir/$fname $user@$name:$pdir
			rsync -rvl $pdir/$fname $user@$name:$pdir
	fi
	time=$time+1
done
